import type { Job, UserProfile, Proposal, Review, Conversation, Message } from "./types";

export const MOCK_JOBS: Job[] = [
  {
    id: "job-1",
    title: "Build a DeFi Dashboard with Next.js & Solana",
    description:
      "We need an experienced developer to build a comprehensive DeFi dashboard that integrates with Solana blockchain. The dashboard should display portfolio values, token balances, staking rewards, and historical performance charts. Must have experience with @solana/web3.js and React.\n\nKey requirements:\n- Real-time price feeds via WebSocket\n- Wallet integration (Phantom, Backpack)\n- Charts with Recharts or Chart.js\n- Responsive design\n- TypeScript required",
    clientWallet: "8xKX3mN7QpZ2vR5tY9wL1jH4bC6dF0eG",
    clientName: "CryptoVentures DAO",
    clientAvatar: "",
    budget: 3500,
    status: "open",
    category: "Web Development",
    tags: ["React", "Solana", "TypeScript", "DeFi", "Next.js"],
    milestones: [
      {
        id: "m1",
        title: "UI/UX Design & Wireframes",
        description: "Design all screens and create interactive prototype",
        amount: 700,
        status: "pending",
        dueDate: "2024-07-15",
      },
      {
        id: "m2",
        title: "Wallet Integration & Data Fetching",
        description: "Implement wallet connections and blockchain data queries",
        amount: 1400,
        status: "pending",
        dueDate: "2024-07-30",
      },
      {
        id: "m3",
        title: "Charts & Final Delivery",
        description: "Implement all charts, testing, and deployment",
        amount: 1400,
        status: "pending",
        dueDate: "2024-08-15",
      },
    ],
    proposals: 7,
    createdAt: "2024-06-20T10:00:00Z",
    deadline: "2024-08-15",
    escrowAddress: "",
    escrowAmount: 0,
    escrowReleased: 0,
  },
  {
    id: "job-2",
    title: "Solana NFT Marketplace Smart Contract Audit",
    description:
      "Looking for a smart contract security auditor to review our NFT marketplace program built with Anchor framework. The contract handles listings, auctions, royalties, and escrow.\n\nScope:\n- ~2,000 lines of Rust/Anchor code\n- Review for common vulnerabilities (reentrancy, overflow, etc.)\n- Detailed audit report with severity ratings\n- Remediation guidance",
    clientWallet: "3mP9rQ2sT6uV8wX0yZ1aB4cD7eF5gH",
    clientName: "NFT Labs",
    clientAvatar: "",
    budget: 5000,
    status: "open",
    category: "Smart Contracts",
    tags: ["Rust", "Anchor", "Security", "Audit", "Solana"],
    milestones: [
      {
        id: "m1",
        title: "Initial Review & Threat Modeling",
        description: "Preliminary code review and threat modeling document",
        amount: 1500,
        status: "pending",
        dueDate: "2024-07-10",
      },
      {
        id: "m2",
        title: "Full Audit Report",
        description: "Comprehensive audit report with all findings",
        amount: 2500,
        status: "pending",
        dueDate: "2024-07-25",
      },
      {
        id: "m3",
        title: "Remediation Review",
        description: "Review of implemented fixes",
        amount: 1000,
        status: "pending",
        dueDate: "2024-08-05",
      },
    ],
    proposals: 3,
    createdAt: "2024-06-18T14:30:00Z",
    deadline: "2024-08-05",
  },
  {
    id: "job-3",
    title: "Web3 Brand Identity & UI Design System",
    description:
      "We're launching a new Solana-based gaming protocol and need a complete brand identity and design system. This includes logo design, color palette, typography, and a full component library in Figma.\n\nDeliverables:\n- Logo suite (light/dark variants)\n- Brand guidelines PDF\n- Figma component library (50+ components)\n- Landing page design (3 breakpoints)",
    clientWallet: "7nJ2kL5mN8oP1qR4sT",
    clientName: "GameFi Protocol",
    clientAvatar: "",
    budget: 2200,
    status: "in_progress",
    category: "UI/UX Design",
    tags: ["Figma", "Branding", "UI Design", "Web3", "Design System"],
    milestones: [
      {
        id: "m1",
        title: "Brand Identity",
        description: "Logo and brand guidelines",
        amount: 800,
        status: "approved",
        dueDate: "2024-06-25",
        completedAt: "2024-06-24T09:00:00Z",
      },
      {
        id: "m2",
        title: "Component Library",
        description: "Figma component library",
        amount: 900,
        status: "in_progress",
        dueDate: "2024-07-10",
      },
      {
        id: "m3",
        title: "Landing Page Design",
        description: "Full landing page Figma file",
        amount: 500,
        status: "pending",
        dueDate: "2024-07-20",
      },
    ],
    proposals: 12,
    createdAt: "2024-06-10T08:00:00Z",
    deadline: "2024-07-20",
    escrowAmount: 2200,
    escrowReleased: 800,
  },
  {
    id: "job-4",
    title: "Anchor Program for Token Vesting Schedule",
    description:
      "Need an Anchor program that implements a token vesting schedule with cliff and linear vesting. The program should support multiple beneficiaries, configurable vesting periods, early withdrawal penalties, and admin controls for revoking unvested tokens.\n\nTech stack: Rust, Anchor Framework, SPL Token program",
    clientWallet: "2bC5dE8fG1hI4jK7lM",
    clientName: "StartupDAO",
    budget: 4800,
    status: "open",
    category: "Smart Contracts",
    tags: ["Rust", "Anchor", "SPL Token", "Vesting", "Solana"],
    milestones: [
      {
        id: "m1",
        title: "Program Architecture & Tests",
        description: "Program design doc and test suite skeleton",
        amount: 1200,
        status: "pending",
      },
      {
        id: "m2",
        title: "Core Vesting Logic",
        description: "Implement vesting schedule and claim logic",
        amount: 2400,
        status: "pending",
      },
      {
        id: "m3",
        title: "Admin Controls & Audit Prep",
        description: "Admin functions, documentation, audit preparation",
        amount: 1200,
        status: "pending",
      },
    ],
    proposals: 5,
    createdAt: "2024-06-22T11:00:00Z",
    deadline: "2024-08-01",
  },
  {
    id: "job-5",
    title: "Technical Documentation for Solana SDK",
    description:
      "We need a technical writer with Solana/blockchain experience to write comprehensive documentation for our SDK. This includes API reference, getting started guides, tutorials, and integration examples in TypeScript and Rust.",
    clientWallet: "9pQ3rS6tU0vW2xY5zA",
    clientName: "SolDev Inc",
    budget: 1500,
    status: "open",
    category: "Technical Writing",
    tags: ["Documentation", "Solana", "TypeScript", "Rust", "SDK"],
    milestones: [
      {
        id: "m1",
        title: "API Reference Docs",
        description: "Complete API reference documentation",
        amount: 700,
        status: "pending",
      },
      {
        id: "m2",
        title: "Tutorials & Examples",
        description: "Getting started guides and code examples",
        amount: 800,
        status: "pending",
      },
    ],
    proposals: 9,
    createdAt: "2024-06-21T16:00:00Z",
    deadline: "2024-07-15",
  },
  {
    id: "job-6",
    title: "Mobile Wallet App (React Native + Solana)",
    description:
      "Build a non-custodial Solana mobile wallet using React Native. Features: seed phrase generation/import, SOL/SPL token send/receive, transaction history, QR code scanning, and biometric auth.",
    clientWallet: "4cD7eF0gH3iJ6kL9mN",
    clientName: "WalletCo",
    budget: 8000,
    status: "completed",
    category: "Mobile Development",
    tags: ["React Native", "Solana", "Mobile", "Wallet", "TypeScript"],
    milestones: [
      {
        id: "m1",
        title: "Core Wallet Functions",
        description: "Key generation, send/receive",
        amount: 3000,
        status: "paid",
        completedAt: "2024-05-20T10:00:00Z",
      },
      {
        id: "m2",
        title: "UI/UX & Token Support",
        description: "Full UI and SPL token support",
        amount: 3000,
        status: "paid",
        completedAt: "2024-06-05T10:00:00Z",
      },
      {
        id: "m3",
        title: "Biometric Auth & Polish",
        description: "Final features and app store prep",
        amount: 2000,
        status: "paid",
        completedAt: "2024-06-18T10:00:00Z",
      },
    ],
    proposals: 15,
    createdAt: "2024-04-15T09:00:00Z",
    deadline: "2024-06-20",
    escrowAmount: 8000,
    escrowReleased: 8000,
  },
];

export const MOCK_PROFILES: UserProfile[] = [
  {
    wallet: "Dev1WaLLet1111111111111111111111111111111111",
    name: "Alex Rivera",
    avatar: "",
    bio: "Full-stack Solana developer with 4 years of experience building DeFi protocols, NFT marketplaces, and dApps. Rust & TypeScript specialist.",
    skills: ["Rust", "Anchor", "TypeScript", "React", "Solana", "DeFi"],
    hourlyRate: 120,
    totalEarned: 48500,
    jobsCompleted: 23,
    avgRating: 4.9,
    reviewCount: 21,
    memberSince: "2021-03-15",
    activeJobs: [MOCK_JOBS[2]],
    reviews: [
      {
        id: "r1",
        jobId: "job-6",
        jobTitle: "Mobile Wallet App (React Native + Solana)",
        reviewerWallet: "4cD7eF0gH3iJ6kL9mN",
        reviewerName: "WalletCo",
        targetWallet: "Dev1WaLLet1111111111111111111111111111111111",
        rating: 5,
        comment:
          "Alex delivered an exceptional mobile wallet app. Clean code, great communication, and delivered ahead of schedule. Highly recommend!",
        createdAt: "2024-06-19T12:00:00Z",
      },
      {
        id: "r2",
        jobId: "job-old-1",
        jobTitle: "DeFi Staking Protocol",
        reviewerWallet: "SomeClient111",
        reviewerName: "DeFi Ventures",
        targetWallet: "Dev1WaLLet1111111111111111111111111111111111",
        rating: 5,
        comment:
          "Outstanding work on our staking protocol. Alex caught several edge cases we missed and the final product was rock solid.",
        createdAt: "2024-04-10T09:00:00Z",
      },
      {
        id: "r3",
        jobId: "job-old-2",
        jobTitle: "NFT Mint Program",
        reviewerWallet: "AnotherClient222",
        reviewerName: "ArtBlock DAO",
        targetWallet: "Dev1WaLLet1111111111111111111111111111111111",
        rating: 4,
        comment:
          "Good work overall. Minor delays but the final delivery was high quality. Would hire again.",
        createdAt: "2024-02-28T14:00:00Z",
      },
    ],
  },
];

export const MOCK_PROPOSALS: Proposal[] = [
  {
    id: "prop-1",
    jobId: "job-1",
    jobTitle: "Build a DeFi Dashboard with Next.js & Solana",
    freelancerWallet: "Dev1WaLLet1111111111111111111111111111111111",
    freelancerName: "Alex Rivera",
    coverLetter:
      "I have 4 years of experience building Solana dApps and would love to tackle this dashboard. I've built similar projects for DeFi protocols and can deliver a polished, performant solution.",
    bidAmount: 3200,
    deliveryDays: 45,
    status: "pending",
    createdAt: "2024-06-21T10:00:00Z",
  },
  {
    id: "prop-2",
    jobId: "job-4",
    jobTitle: "Anchor Program for Token Vesting Schedule",
    freelancerWallet: "Dev1WaLLet1111111111111111111111111111111111",
    freelancerName: "Alex Rivera",
    coverLetter:
      "I've implemented several vesting contracts on Solana and am very familiar with the patterns needed here. I can start immediately.",
    bidAmount: 4500,
    deliveryDays: 30,
    status: "accepted",
    createdAt: "2024-06-23T08:00:00Z",
  },
];

export const MOCK_REVIEWS: Review[] = MOCK_PROFILES[0].reviews;

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    participants: ["Dev1WaLLet1111111111111111111111111111111111", "8xKX3mN7QpZ2vR5tY9wL1jH4bC6dF0eG"],
    participantNames: ["Alex Rivera", "CryptoVentures DAO"],
    jobId: "job-1",
    jobTitle: "Build a DeFi Dashboard with Next.js & Solana",
    unreadCount: 2,
    lastMessage: {
      id: "msg-3",
      conversationId: "conv-1",
      senderWallet: "8xKX3mN7QpZ2vR5tY9wL1jH4bC6dF0eG",
      senderName: "CryptoVentures DAO",
      content: "Sounds great! Can you share your previous DeFi project links?",
      timestamp: "2024-06-22T09:30:00Z",
      read: false,
    },
  },
  {
    id: "conv-2",
    participants: ["Dev1WaLLet1111111111111111111111111111111111", "2bC5dE8fG1hI4jK7lM"],
    participantNames: ["Alex Rivera", "StartupDAO"],
    jobId: "job-4",
    jobTitle: "Anchor Program for Token Vesting Schedule",
    unreadCount: 0,
    lastMessage: {
      id: "msg-last",
      conversationId: "conv-2",
      senderWallet: "Dev1WaLLet1111111111111111111111111111111111",
      senderName: "Alex Rivera",
      content: "I'll have the architecture document ready by Friday.",
      timestamp: "2024-06-23T14:00:00Z",
      read: true,
    },
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  "conv-1": [
    {
      id: "msg-1",
      conversationId: "conv-1",
      senderWallet: "Dev1WaLLet1111111111111111111111111111111111",
      senderName: "Alex Rivera",
      content: "Hi! I submitted a proposal for your DeFi dashboard project. I have extensive experience with Solana and would love to discuss the details.",
      timestamp: "2024-06-21T10:05:00Z",
      read: true,
    },
    {
      id: "msg-2",
      conversationId: "conv-1",
      senderWallet: "8xKX3mN7QpZ2vR5tY9wL1jH4bC6dF0eG",
      senderName: "CryptoVentures DAO",
      content: "Thanks for reaching out! Your profile looks impressive. We're looking for someone who can handle real-time WebSocket data feeds. Is that something you're comfortable with?",
      timestamp: "2024-06-22T08:15:00Z",
      read: true,
    },
    {
      id: "msg-3",
      conversationId: "conv-1",
      senderWallet: "Dev1WaLLet1111111111111111111111111111111111",
      senderName: "Alex Rivera",
      content: "Absolutely! I've built several real-time dashboards using WebSockets with Solana's subscription API. I can show you a live demo of a similar project.",
      timestamp: "2024-06-22T09:00:00Z",
      read: true,
    },
    {
      id: "msg-4",
      conversationId: "conv-1",
      senderWallet: "8xKX3mN7QpZ2vR5tY9wL1jH4bC6dF0eG",
      senderName: "CryptoVentures DAO",
      content: "Sounds great! Can you share your previous DeFi project links?",
      timestamp: "2024-06-22T09:30:00Z",
      read: false,
    },
  ],
  "conv-2": [
    {
      id: "msg-a",
      conversationId: "conv-2",
      senderWallet: "Dev1WaLLet1111111111111111111111111111111111",
      senderName: "Alex Rivera",
      content: "Hello! I saw your vesting contract project and I'm very interested. I've implemented 3 similar programs on mainnet.",
      timestamp: "2024-06-23T11:00:00Z",
      read: true,
    },
    {
      id: "msg-b",
      conversationId: "conv-2",
      senderWallet: "2bC5dE8fG1hI4jK7lM",
      senderName: "StartupDAO",
      content: "Great! We accepted your proposal. When can you start?",
      timestamp: "2024-06-23T13:00:00Z",
      read: true,
    },
    {
      id: "msg-last",
      conversationId: "conv-2",
      senderWallet: "Dev1WaLLet1111111111111111111111111111111111",
      senderName: "Alex Rivera",
      content: "I'll have the architecture document ready by Friday.",
      timestamp: "2024-06-23T14:00:00Z",
      read: true,
    },
  ],
};
